### PR TITLE
include API coverage in README

### PR DESCRIPTION
**Pull request by andrewharvey**
The current README says it fully implements classList which initially misled me to believe it supported the `replace` method. This change updates the README to make it clearer what is supported.

Related to #70

### CODE REVIEW

**Comment by eligrey** [comment]
I think it would be easier to just implement replace. I'll look into it when I get time, or you can submit a pull request that implements replace.

**Comment by andrewharvey** [comment]
Sorry I don't have a need for it right now as it's easy enough to work around, so this PR was only meant as a stop gap until someone else implements #70.

**Comment by andrewharvey** [comment]
Oh I just noticed you implemented replace :tada: Thanks.

**Comment by englishextra** [comment]
that's a good thing

**Comment by englishextra** [comment]
@eligrey Are you going to publish 1.2.201711092 to npm?
Can't wait for that

**Pull request closed without merging**
