### PR TITLE
Update classList.js

### PR DESCRIPTION
**Pull request by nbouvrette**
Fixing indentation.

### CODE REVIEW

**Comment by eligrey** [comment]
What's broken?

**Comment by nbouvrette** [comment]
Readability is broken :) Why not merge it? I didn't change anything else.

**Comment by eligrey** [comment]
Do you realize that most editors allow you to configure tab width?

**Comment by nbouvrette** [comment]
I know, I use such an editor myself but the current indentation did not play nice with my editor's "Reformat code" function and I had to use an online JavaScript beautifier to get the indentation back to a more standard state. On the other hand if this indentation is by design I will stop arguing since you are the owner of this script!

**Pull request closed without merging**
