### PR TITLE
Add a package.json file

### PR DESCRIPTION
**Pull request by sroucheray**

### CODE REVIEW

**Comment by sroucheray** [comment]
@eligrey I switched from `mdn-classlist.js` to `classlist.js` but you must be aware that @tbranyen has already registered it to npm https://www.npmjs.com/package/classlist.js

**Comment by tbranyen** [comment]
Hey ya'll, just send me an npm username to replace my own with

**Comment by eligrey** [comment]
I don't really care who publishes it. Do whatever you want (the public domain license also means that I cannot restrict your use in any way whatsoever, even such as requiring attribution) and have at it.

**Comment by eligrey** [comment]
Btw it seems like @tbranyen's entry on npm is up to date, so it seems you no action is necessary on your part.

**Comment by sroucheray** [comment]
Thanks @eligrey !

**Pull request merged**
