### PR TITLE
Update LICENSE.md

### PR DESCRIPTION
**Pull request by mildfuzz**
I need to have an official license on this library to include it in a project. I've forked it and added myself but thought it would make a good pull request :)

### CODE REVIEW

**Comment by eligrey** [comment]
What makes you think this license if unofficial? Is my legalese insufficient for you? The MIT license has even more restrictions than my public domain dedication.

**Comment by mildfuzz** [comment]
updated, this okay?

**Comment by mildfuzz** [comment]
Talk to my client, dude!!

**Comment by eligrey** [comment]
Tell your client that the only difference between the MIT license and this public domain dedication is that the MIT license requires attribution, whereas this does not.

Also "Eli pinky promises not to sue you"

If they insist on the MIT license, go ahead. The whole point of public domain is that you are

**Comment by mildfuzz** [comment]
This is why I have gone down this route, to satisfy a demand without having to do work that's already been done. 

Then figured I would fire off a pull request, just on the off chance. No bother

**Comment by eligrey** [comment]
I've changed the license to something more explicit.

**Comment by beck** [comment]
NPM throws a warning for "Public Domain", here is a pull to specify The Unlicense https://github.com/eligrey/classList.js/pull/56

**Pull request closed without merging**
