### PR TITLE
Improved tests, readability, bugfix

### PR DESCRIPTION
**Pull request by stevenvachon**
Let me know if you want Travis CI and [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) set up.

### CODE REVIEW

**Comment by stevenvachon** [comment]
@eligrey don't fucking die on me.

**Comment by beck** [comment]
This is a fairly large pull and is not the easiest to review. I'm not understanding the title, what is being "unbroken"? Each commit here is broad enough to warrant their own pull.

**Comment by stevenvachon** [comment]
#44

**Comment by mjschlot** [comment]
@beck please see my comment on issue #54 in response to @stevenvachon pointing out his merge. Comment: #issuecomment-244809532

**Comment by beck** [comment]
Instead of continually massaging the boolean, I think removing the `else` around the upgrade code is a simpler solution (and much easier to review):
https://github.com/eligrey/classList.js/pull/57

The whitespace cleanup is definitely needed and should happen in a separate pull.

The test improvements are also great, should also happen in their own pull, and would be nice if they enclosed the changes seen in: https://github.com/eligrey/classList.js/pull/20

**Comment by stevenvachon** [comment]
@eligrey make haste.

**Comment by stevenvachon** [comment]
This project goes nowhere.

**Pull request closed without merging**
