### PR TITLE
Cleanup whitespace

### PR DESCRIPTION
**Pull request by beck**
No functional changes. Easier to review using a diff that doesn't show the whitespace changes:
https://github.com/eligrey/classList.js/pull/62/files?w=1

And cleanup other linting nags such as:
* consistent quotes
* defined globals

### CODE REVIEW

**Comment by englishextra** [comment]
did you incorporate this https://github.com/eligrey/classList.js/pull/57

**Comment by beck** [comment]
> did you incorporate this #57

For sure.

> Thanks for tidying up.

No problem.

Anything that lands here I'm merging down and publishing to:
https://www.npmjs.com/package/classlist-polyfill

**Comment by englishextra** [comment]
@beck Very nice. Thanks. I'm waiting for the new npm publish there, since it's a year ago release.

**Comment by englishextra** [comment]
UPD: can jshint 	```Confusing use of '!'.``` an be resolved for that piece:

```
      DOMTokenList.prototype.toggle = function(token, force) {
        if (1 in arguments && (!this.contains(token) === !force)) {
          return force;
        } else {
          return _toggle.call(this, token);
        }
      };
```

somewhat of a:

```
DOMTokenList.prototype.toggle = function (token, force) {
	var _contains = !this.contains(token),
	_force = !force;
	if (1 in arguments && _contains === _force) {
		return force;
	} else {
		return _toggle.call(this, token);
	}
};
```
I'm not sure if i'm doing it right.

**Comment by beck** [comment]
@englishextra lets save that for a different pull.

It is easier to review changes when not mixing syntax cleanup and logic changes.

**Comment by englishextra** [comment]
@beck Sure

**Comment by beck** [comment]
@englishextra released: https://github.com/yola/classlist-polyfill/releases/tag/1.2.0

**Comment by englishextra** [comment]
@beck Good news, and thanks for ```toggle```.

**Comment by beck** [comment]
Closing this for now. Will reopen once there are better tests in place to verify this change is valid.

**Pull request closed without merging**
