### PR TITLE
need to update minified file

### PR DESCRIPTION
**Pull request by allannienhuis**
The minified file is out of date.  Angularjs2 team is using the outdated version in their shims_for_IE.js file.  I stumbled across the svg issue in IE11.  I'll be sending them pull request for this as well.

I minified the file using uglifyjs as follows:
uglifyjs classList.js > classList.min.js -m

Not sure what you were using to minify the file originally. :)

### CODE REVIEW

**Comment by eligrey** [comment]
Oh thanks for catching that. I forgot to update it.

**Comment by RoyEJohnson** [comment]
There may be a problem with the new file. We have been using classList.min.js (via rawgit) and now IE11 acts as though it has no shim.

**Comment by allannienhuis** [comment]
thanks, I'll retest and comment back here.

**Comment by allannienhuis** [comment]
Can you try this plunkr? https://plnkr.co/edit/jALLcYE3zvxYeYZ0O5Dh

I am only testing for the existence of the classList function, as I simply minified the lastest unminified code.  

I get the same results in both minified and unminified version of the file. If we don't include either polyfill, the classList function does not exist on svg elements on IE11, as expected.

If the latest unminified file has other functional changes you're seeing from the older minified file then perhaps that's a separate issue :)

**Comment by RoyEJohnson** [comment]
It's the older-minified-file situation. I found it in the Issues here: https://github.com/eligrey/classList.js/issues/44
I'm pulling https://cdn.rawgit.com/eligrey/classList.js/e87db36a95b2381a8c3ed44582a3926185cede70/classList.min.js now.

**Comment by allannienhuis** [comment]
ah, that's interesting. so failing the check doesn't simply skip the polyfill, it runs different code that patches just a couple of the classlist functions (which you need).  That's not that clear if you're just looking at that initial test :)

So the work to include the polyfill for svg elements should probably be separated out, so it could be applied to svg elements only (if needed), leaving the dom element prototype intact.

and then, that second branch that patches those specific functions should be run in every case, and updated to handle svg elements as well.

**Comment by allannienhuis** [comment]
@RoyEJohnson, I have a change that might resolve your issue while still applying the polyfill for SVG elements.  I understand you might not care about SVG support, but would you mind trying this:
https://rawgit.com/allannienhuis/classList.js/master/classList.min.js
or https://rawgit.com/allannienhuis/classList.js/master/classList.js

This change applies the full polyfill if needed, so that svg elements get the polyfill, but also applies the partial patch to support IE that is being skipped in the latest version here (the cause of the problem you saw).  If it passes your test, I'll submit PR for Eli.

I'm not really certain this will work, as the partial polyfills should not pass their tests to be applied after receiving the full polyfill, but I'm not sure exactly what failed for you to know for sure. :)

Cheers,

**Pull request merged**
