### PR TITLE
Always check & upgrade partial implementations.

### PR DESCRIPTION
**Pull request by beck**
Tests are failing in IE, the partial implementation of `toggle` is not
being upgraded.

The branching logic is broken, IE no longer falls into the `else` block
since SVG checks were added.

Since the `else` does not provide much value, removing is a simple fix.

ping @eligrey 

fixes: https://github.com/eligrey/classList.js/issues/54 https://github.com/eligrey/classList.js/issues/44

### CODE REVIEW

**Comment by mjschlot** [comment]
@eligrey I know your quite busy. So I am wondering if there is anybody else with the ability to accept the pull request? I believe @beck's solution is solid and think it is ready to accept. Thanks.

**Comment by jay8t6** [comment]
@eligrey this fixes a problem that I was facing with a classList implementation on non-svg elements. Can we get this merged please?

**Comment by eligrey** [comment]
Sorry about that, I've been very busy.

**Comment by eligrey** [comment]
Released as [v1.1.20170427](https://github.com/eligrey/classList.js/releases/tag/1.1.20170427).

**Comment by jay8t6** [comment]
Thank you!!

**Comment by phueper** [comment]
Thank you! Could you also npm publish to https://www.npmjs.com/package/classlist.js  ?

**Comment by eligrey** [comment]
@phueper you'll want to ask @tbranyen

@tbranyen mind updating https://www.npmjs.com/package/classlist.js to [version https://github.com/eligrey/classList.js/releases/tag/1.1.20170427]()?

**Comment by phueper** [comment]
@eligrey yes, sorry, i just realized that he was the npm package owner ... thanks again :)

**Comment by stevenvachon** [comment]
Almost the worst package management ever.

**Comment by tbranyen** [comment]
Yo Yo. I can do this @eligrey would you like me to add you as an owner and drop myself?

**Comment by beck** [comment]
Published: https://github.com/yola/classlist-polyfill/releases/tag/1.2.0

**Comment by stevenvachon** [comment]
@tbranyen please deprecate this package.

**Comment by tbranyen** [comment]
I will absolutely do that, once I get one more person to validate that request. @eligrey looking for some guidance here.

**Comment by beck** [comment]
@tbranyen hold off for a little bit? Honestly, I would love to deprecate our fork. Lets wait for a reply.

Also, lets move the conversation off of this pr: https://github.com/eligrey/classList.js/issues/63

**Pull request merged**
